"""Thin pipeline entry points for additive Phase 1 wiring."""

from pipeline.baselines import (
    run_behavioral_profiling,
    run_build_baselines,
    run_peer_clustering,
)
from pipeline.case_actions import generate_suggested_actions
from pipeline.case_enrichment import run_opencti_enrichment
from pipeline.case_finalize import finalize_case_analysis_run
from pipeline.case_narrative import run_ai_synthesis, run_ai_triage
from pipeline.case_timeline import run_incident_storylines, run_ioc_timeline
from pipeline.detect_anomalies import run_detect_anomalies
from pipeline.detect import run_hayabusa_correlation
from pipeline.pattern_analysis import (
    annotate_task_pattern_overlaps,
    build_task_ai_pattern_completion_meta,
    build_pattern_threat_intel_context,
    build_task_ai_pattern_progress_meta,
    cleanup_task_pattern_extractor,
    complete_case_pattern_run,
    complete_task_ai_pattern_run,
    create_candidate_extractor,
    create_evidence_engine,
    execute_task_ai_pattern,
    evaluate_ai_pattern,
    evaluate_pattern_packages,
    evaluate_pattern_suppression,
    evaluate_rule_based_pattern,
    execute_case_ai_pattern,
    finalize_task_ai_pattern_results,
    load_pattern_configs,
    log_task_ai_pattern_completion,
    materialize_pattern_package,
    persist_rule_based_pattern_results,
    prepare_case_pattern_runtime,
    prepare_case_pattern_head,
    prepare_case_pattern_inputs,
    prepare_pattern_analysis,
    prepare_task_ai_pattern_inputs,
    run_case_pattern_loop,
    run_case_pattern_iteration,
    run_task_ai_pattern_iteration,
    process_ai_pattern_packages,
    persist_ai_pattern_results,
    run_pattern_census,
    select_highest_scoring_packages,
    should_run_pattern,
)

__all__ = [
    "annotate_task_pattern_overlaps",
    "build_task_ai_pattern_completion_meta",
    "build_pattern_threat_intel_context",
    "build_task_ai_pattern_progress_meta",
    "cleanup_task_pattern_extractor",
    "complete_case_pattern_run",
    "complete_task_ai_pattern_run",
    "generate_suggested_actions",
    "finalize_case_analysis_run",
    "create_candidate_extractor",
    "create_evidence_engine",
    "execute_task_ai_pattern",
    "evaluate_ai_pattern",
    "evaluate_pattern_packages",
    "evaluate_pattern_suppression",
    "evaluate_rule_based_pattern",
    "execute_case_ai_pattern",
    "finalize_task_ai_pattern_results",
    "load_pattern_configs",
    "log_task_ai_pattern_completion",
    "materialize_pattern_package",
    "persist_rule_based_pattern_results",
    "prepare_case_pattern_runtime",
    "prepare_case_pattern_head",
    "prepare_case_pattern_inputs",
    "prepare_pattern_analysis",
    "prepare_task_ai_pattern_inputs",
    "run_case_pattern_loop",
    "run_case_pattern_iteration",
    "run_task_ai_pattern_iteration",
    "process_ai_pattern_packages",
    "persist_ai_pattern_results",
    "run_behavioral_profiling",
    "run_build_baselines",
    "run_incident_storylines",
    "run_ioc_timeline",
    "run_opencti_enrichment",
    "run_ai_synthesis",
    "run_ai_triage",
    "run_detect_anomalies",
    "run_pattern_census",
    "run_peer_clustering",
    "run_hayabusa_correlation",
    "select_highest_scoring_packages",
    "should_run_pattern",
]
